name: tmdb_api_kit
description: A comprehensive Dart package for interacting with The Movie Database (TMDB) API. Provides type-safe access to movies, TV shows, search functionality, and detailed media information.
version: 1.0.0
repository: https://github.com/poypoy252525/tmdb_api
homepage: https://github.com/poypoy252525/tmdb_api
issue_tracker: https://github.com/poypoy252525/tmdb_api/issues

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
